/*
 * Open Education API
 * OpenAPI (fka Swagger) specification for the Open Education API.  <figure>  <a target=\"_blank\" href=\"OOAPIv5_model.png\">   <img src=\"OOAPIv5_model.png\" alt=\"OOAPI information model that feeds OOAPI specification\" width=\"70%\" class=\"img-responsive\">   </a>   <figcaption> OOAPI information model that feeds OOAPI specification (click to enlage)</figcaption> </figure>  The model provides an overview of how the objects on which the API is specified are related. The overarching concept educations is not found in the in the end points of the API. The smaller concepts of programOffering, courseOffering and conceptOffering are all found in the offering endpoint. The different types of association can all be found in the association endpoint.  The original file for this model can be found <a target=\"_blank\" href=\"OOAPIv5_model_v0.4.drawio\">here</a>  The program relations object is not found as a separate endpoint but relations between programs can be found within the program endpoint by expanding that endpoint.  Information about earlier meetings and presentations can be found <a target=\"_blank\" href=\"https://github.com/open-education-api/notulen\">here</a>  Information on the EDU-API model that was also used for this api is shown <a target=\"_blank\" href=\"eduapi.png\">here</a> 
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.net.URI;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.Address;
import org.openapitools.client.model.Consumer;
import org.openapitools.client.model.CourseAllOf;
import org.openapitools.client.model.CourseId;
import org.openapitools.client.model.CourseProperties;
import org.openapitools.client.model.CoursePropertiesEducationSpecification;
import org.openapitools.client.model.CoursePropertiesOrganization;
import org.openapitools.client.model.IdentifierEntry;
import org.openapitools.client.model.LanguageTypedString;
import org.openapitools.client.model.Level;
import org.openapitools.client.model.ProgramPropertiesChildrenInner;
import org.openapitools.client.model.ProgramPropertiesCoordinatorsInner;
import org.openapitools.client.model.StudyLoadDescriptor;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Course
 */
@JsonPropertyOrder({
  Course.JSON_PROPERTY_COURSE_ID,
  Course.JSON_PROPERTY_PRIMARY_CODE,
  Course.JSON_PROPERTY_NAME,
  Course.JSON_PROPERTY_ABBREVIATION,
  Course.JSON_PROPERTY_STUDY_LOAD,
  Course.JSON_PROPERTY_MODE_OF_DELIVERY,
  Course.JSON_PROPERTY_DURATION,
  Course.JSON_PROPERTY_FIRST_START_DATE,
  Course.JSON_PROPERTY_DESCRIPTION,
  Course.JSON_PROPERTY_TEACHING_LANGUAGE,
  Course.JSON_PROPERTY_FIELDS_OF_STUDY,
  Course.JSON_PROPERTY_LEARNING_OUTCOMES,
  Course.JSON_PROPERTY_ADMISSION_REQUIREMENTS,
  Course.JSON_PROPERTY_QUALIFICATION_REQUIREMENTS,
  Course.JSON_PROPERTY_LEVEL,
  Course.JSON_PROPERTY_ENROLLMENT,
  Course.JSON_PROPERTY_RESOURCES,
  Course.JSON_PROPERTY_ASSESSMENT,
  Course.JSON_PROPERTY_LINK,
  Course.JSON_PROPERTY_EDUCATION_SPECIFICATION,
  Course.JSON_PROPERTY_ADDRESSES,
  Course.JSON_PROPERTY_OTHER_CODES,
  Course.JSON_PROPERTY_CONSUMERS,
  Course.JSON_PROPERTY_EXT,
  Course.JSON_PROPERTY_PROGRAMS,
  Course.JSON_PROPERTY_COORDINATORS,
  Course.JSON_PROPERTY_ORGANIZATION,
  Course.JSON_PROPERTY_VALID_FROM,
  Course.JSON_PROPERTY_VALID_TO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-04T10:32:49.151315+02:00[Europe/Amsterdam]")
public class Course {
  public static final String JSON_PROPERTY_COURSE_ID = "courseId";
  private UUID courseId;

  public static final String JSON_PROPERTY_PRIMARY_CODE = "primaryCode";
  private IdentifierEntry primaryCode;

  public static final String JSON_PROPERTY_NAME = "name";
  private List<LanguageTypedString> name = new ArrayList<>();

  public static final String JSON_PROPERTY_ABBREVIATION = "abbreviation";
  private String abbreviation;

  public static final String JSON_PROPERTY_STUDY_LOAD = "studyLoad";
  private StudyLoadDescriptor studyLoad;

  /**
   * Gets or Sets modeOfDelivery
   */
  public enum ModeOfDeliveryEnum {
    DISTANCE_LEARNING("distance-learning"),
    
    ON_CAMPUS("on campus"),
    
    ONLINE("online"),
    
    HYBRID("hybrid"),
    
    SITUATED("situated");

    private String value;

    ModeOfDeliveryEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ModeOfDeliveryEnum fromValue(String value) {
      for (ModeOfDeliveryEnum b : ModeOfDeliveryEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_MODE_OF_DELIVERY = "modeOfDelivery";
  private List<ModeOfDeliveryEnum> modeOfDelivery = null;

  public static final String JSON_PROPERTY_DURATION = "duration";
  private String duration;

  public static final String JSON_PROPERTY_FIRST_START_DATE = "firstStartDate";
  private LocalDate firstStartDate;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private List<LanguageTypedString> description = new ArrayList<>();

  public static final String JSON_PROPERTY_TEACHING_LANGUAGE = "teachingLanguage";
  private String teachingLanguage;

  public static final String JSON_PROPERTY_FIELDS_OF_STUDY = "fieldsOfStudy";
  private String fieldsOfStudy;

  public static final String JSON_PROPERTY_LEARNING_OUTCOMES = "learningOutcomes";
  private List<List<LanguageTypedString>> learningOutcomes = null;

  public static final String JSON_PROPERTY_ADMISSION_REQUIREMENTS = "admissionRequirements";
  private List<LanguageTypedString> admissionRequirements = null;

  public static final String JSON_PROPERTY_QUALIFICATION_REQUIREMENTS = "qualificationRequirements";
  private List<LanguageTypedString> qualificationRequirements = null;

  public static final String JSON_PROPERTY_LEVEL = "level";
  private Level level;

  public static final String JSON_PROPERTY_ENROLLMENT = "enrollment";
  private List<LanguageTypedString> enrollment = null;

  public static final String JSON_PROPERTY_RESOURCES = "resources";
  private List<String> resources = null;

  public static final String JSON_PROPERTY_ASSESSMENT = "assessment";
  private List<LanguageTypedString> assessment = null;

  public static final String JSON_PROPERTY_LINK = "link";
  private URI link;

  public static final String JSON_PROPERTY_EDUCATION_SPECIFICATION = "educationSpecification";
  private CoursePropertiesEducationSpecification educationSpecification;

  public static final String JSON_PROPERTY_ADDRESSES = "addresses";
  private List<Address> addresses = null;

  public static final String JSON_PROPERTY_OTHER_CODES = "otherCodes";
  private List<IdentifierEntry> otherCodes = null;

  public static final String JSON_PROPERTY_CONSUMERS = "consumers";
  private List<Consumer> consumers = null;

  public static final String JSON_PROPERTY_EXT = "ext";
  private Object ext;

  public static final String JSON_PROPERTY_PROGRAMS = "programs";
  private List<ProgramPropertiesChildrenInner> programs = null;

  public static final String JSON_PROPERTY_COORDINATORS = "coordinators";
  private List<ProgramPropertiesCoordinatorsInner> coordinators = null;

  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  private CoursePropertiesOrganization organization;

  public static final String JSON_PROPERTY_VALID_FROM = "validFrom";
  private LocalDate validFrom;

  public static final String JSON_PROPERTY_VALID_TO = "validTo";
  private LocalDate validTo;

  public Course() { 
  }

  @JsonCreator
  public Course(
    @JsonProperty(JSON_PROPERTY_COURSE_ID) UUID courseId
  ) {
    this();
    this.courseId = courseId;
  }

   /**
   * Unique id of this course
   * @return courseId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "123e4567-e89b-12d3-a456-426614174000", required = true, value = "Unique id of this course")
  @JsonProperty(JSON_PROPERTY_COURSE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getCourseId() {
    return courseId;
  }




  public Course primaryCode(IdentifierEntry primaryCode) {
    
    this.primaryCode = primaryCode;
    return this;
  }

   /**
   * Get primaryCode
   * @return primaryCode
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PRIMARY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public IdentifierEntry getPrimaryCode() {
    return primaryCode;
  }


  @JsonProperty(JSON_PROPERTY_PRIMARY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrimaryCode(IdentifierEntry primaryCode) {
    this.primaryCode = primaryCode;
  }


  public Course name(List<LanguageTypedString> name) {
    
    this.name = name;
    return this;
  }

  public Course addNameItem(LanguageTypedString nameItem) {
    this.name.add(nameItem);
    return this;
  }

   /**
   * The name of this course (ECTS-title)
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "[{language=en-GB, value=Academic and Professional Writing}]", required = true, value = "The name of this course (ECTS-title)")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<LanguageTypedString> getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(List<LanguageTypedString> name) {
    this.name = name;
  }


  public Course abbreviation(String abbreviation) {
    
    this.abbreviation = abbreviation;
    return this;
  }

   /**
   * The abbreviation or internal code used to identify this course (ECTS-code)
   * @return abbreviation
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "INFOMQNM", required = true, value = "The abbreviation or internal code used to identify this course (ECTS-code)")
  @JsonProperty(JSON_PROPERTY_ABBREVIATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAbbreviation() {
    return abbreviation;
  }


  @JsonProperty(JSON_PROPERTY_ABBREVIATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAbbreviation(String abbreviation) {
    this.abbreviation = abbreviation;
  }


  public Course studyLoad(StudyLoadDescriptor studyLoad) {
    
    this.studyLoad = studyLoad;
    return this;
  }

   /**
   * Get studyLoad
   * @return studyLoad
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STUDY_LOAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StudyLoadDescriptor getStudyLoad() {
    return studyLoad;
  }


  @JsonProperty(JSON_PROPERTY_STUDY_LOAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStudyLoad(StudyLoadDescriptor studyLoad) {
    this.studyLoad = studyLoad;
  }


  public Course modeOfDelivery(List<ModeOfDeliveryEnum> modeOfDelivery) {
    
    this.modeOfDelivery = modeOfDelivery;
    return this;
  }

  public Course addModeOfDeliveryItem(ModeOfDeliveryEnum modeOfDeliveryItem) {
    if (this.modeOfDelivery == null) {
      this.modeOfDelivery = new ArrayList<>();
    }
    this.modeOfDelivery.add(modeOfDeliveryItem);
    return this;
  }

   /**
   * The mode of delivery of the component (ECTS-mode of delivery) - distance-learning: afstandsleren - on campus: op de campus - online: online - hybrid: hybride - situated: op locatie 
   * @return modeOfDelivery
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The mode of delivery of the component (ECTS-mode of delivery) - distance-learning: afstandsleren - on campus: op de campus - online: online - hybrid: hybride - situated: op locatie ")
  @JsonProperty(JSON_PROPERTY_MODE_OF_DELIVERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ModeOfDeliveryEnum> getModeOfDelivery() {
    return modeOfDelivery;
  }


  @JsonProperty(JSON_PROPERTY_MODE_OF_DELIVERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModeOfDelivery(List<ModeOfDeliveryEnum> modeOfDelivery) {
    this.modeOfDelivery = modeOfDelivery;
  }


  public Course duration(String duration) {
    
    this.duration = duration;
    return this;
  }

   /**
   * The duration of this course. The duration format is from the ISO 8601 ABNF as given in Appendix A of RFC 3339.
   * @return duration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "P1DT30H4S", value = "The duration of this course. The duration format is from the ISO 8601 ABNF as given in Appendix A of RFC 3339.")
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDuration() {
    return duration;
  }


  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDuration(String duration) {
    this.duration = duration;
  }


  public Course firstStartDate(LocalDate firstStartDate) {
    
    this.firstStartDate = firstStartDate;
    return this;
  }

   /**
   * The date when participants can follow this course for the first time.
   * @return firstStartDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date when participants can follow this course for the first time.")
  @JsonProperty(JSON_PROPERTY_FIRST_START_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getFirstStartDate() {
    return firstStartDate;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_START_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstStartDate(LocalDate firstStartDate) {
    this.firstStartDate = firstStartDate;
  }


  public Course description(List<LanguageTypedString> description) {
    
    this.description = description;
    return this;
  }

  public Course addDescriptionItem(LanguageTypedString descriptionItem) {
    this.description.add(descriptionItem);
    return this;
  }

   /**
   * The description of this course (ECTS-description).
   * @return description
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "[{language=en-GB, value=As with all empirical sciences, to assure valid outcomes, HCI studies heavily rely on research methods and statistics. This holds for the design of user interfaces, personalized recommender systems, and interaction paradigms for the internet of things. This course prepares you to do so by learning you to collect data, design experiments, and analyze the results. By the end of the course, you will have a detailed understanding of how to select and apply quantitative research methods and analysis to address virtually all HCI challenges. Quantitative research and data analysis will be taught in the context of state-of-the-art HCI challenges. Lectures will be alternated with hands-on learning, including work with predefined datasets (e.g., addressing facial features, cognitive load, and emotion). Additionally, students will set up their own research (e.g., using eye tracking). Data processing and analysis will be executed using R.}]", required = true, value = "The description of this course (ECTS-description).")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<LanguageTypedString> getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(List<LanguageTypedString> description) {
    this.description = description;
  }


  public Course teachingLanguage(String teachingLanguage) {
    
    this.teachingLanguage = teachingLanguage;
    return this;
  }

   /**
   * The (primary) teaching language in which this course is given, should be a three-letter language code as specified by ISO 639-2.
   * @return teachingLanguage
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "nld", required = true, value = "The (primary) teaching language in which this course is given, should be a three-letter language code as specified by ISO 639-2.")
  @JsonProperty(JSON_PROPERTY_TEACHING_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTeachingLanguage() {
    return teachingLanguage;
  }


  @JsonProperty(JSON_PROPERTY_TEACHING_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTeachingLanguage(String teachingLanguage) {
    this.teachingLanguage = teachingLanguage;
  }


  public Course fieldsOfStudy(String fieldsOfStudy) {
    
    this.fieldsOfStudy = fieldsOfStudy;
    return this;
  }

   /**
   * Field(s) of study (e.g. ISCED-F) (http://uis.unesco.org/sites/default/files/documents/isced-fields-of-education-and-training-2013-en.pdf.
   * @return fieldsOfStudy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0732", value = "Field(s) of study (e.g. ISCED-F) (http://uis.unesco.org/sites/default/files/documents/isced-fields-of-education-and-training-2013-en.pdf.")
  @JsonProperty(JSON_PROPERTY_FIELDS_OF_STUDY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFieldsOfStudy() {
    return fieldsOfStudy;
  }


  @JsonProperty(JSON_PROPERTY_FIELDS_OF_STUDY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFieldsOfStudy(String fieldsOfStudy) {
    this.fieldsOfStudy = fieldsOfStudy;
  }


  public Course learningOutcomes(List<List<LanguageTypedString>> learningOutcomes) {
    
    this.learningOutcomes = learningOutcomes;
    return this;
  }

  public Course addLearningOutcomesItem(List<LanguageTypedString> learningOutcomesItem) {
    if (this.learningOutcomes == null) {
      this.learningOutcomes = new ArrayList<>();
    }
    this.learningOutcomes.add(learningOutcomesItem);
    return this;
  }

   /**
   * Statements that describe the knowledge or skills students should acquire by the end of a particular course (ECTS-learningoutcome).
   * @return learningOutcomes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Statements that describe the knowledge or skills students should acquire by the end of a particular course (ECTS-learningoutcome).")
  @JsonProperty(JSON_PROPERTY_LEARNING_OUTCOMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<List<LanguageTypedString>> getLearningOutcomes() {
    return learningOutcomes;
  }


  @JsonProperty(JSON_PROPERTY_LEARNING_OUTCOMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLearningOutcomes(List<List<LanguageTypedString>> learningOutcomes) {
    this.learningOutcomes = learningOutcomes;
  }


  public Course admissionRequirements(List<LanguageTypedString> admissionRequirements) {
    
    this.admissionRequirements = admissionRequirements;
    return this;
  }

  public Course addAdmissionRequirementsItem(LanguageTypedString admissionRequirementsItem) {
    if (this.admissionRequirements == null) {
      this.admissionRequirements = new ArrayList<>();
    }
    this.admissionRequirements.add(admissionRequirementsItem);
    return this;
  }

   /**
   * This information may be given at an institutional level and/or at the level of individual programmes. Make sure that it is clear whether the information applies to fee-paying students (national and/or international) or to exchange students.
   * @return admissionRequirements
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[{language=en-GB, value=Students need to be enrolled at qualifying institutions of higher education that participate in this alliance}]", value = "This information may be given at an institutional level and/or at the level of individual programmes. Make sure that it is clear whether the information applies to fee-paying students (national and/or international) or to exchange students.")
  @JsonProperty(JSON_PROPERTY_ADMISSION_REQUIREMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<LanguageTypedString> getAdmissionRequirements() {
    return admissionRequirements;
  }


  @JsonProperty(JSON_PROPERTY_ADMISSION_REQUIREMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdmissionRequirements(List<LanguageTypedString> admissionRequirements) {
    this.admissionRequirements = admissionRequirements;
  }


  public Course qualificationRequirements(List<LanguageTypedString> qualificationRequirements) {
    
    this.qualificationRequirements = qualificationRequirements;
    return this;
  }

  public Course addQualificationRequirementsItem(LanguageTypedString qualificationRequirementsItem) {
    if (this.qualificationRequirements == null) {
      this.qualificationRequirements = new ArrayList<>();
    }
    this.qualificationRequirements.add(qualificationRequirementsItem);
    return this;
  }

   /**
   * Normally, students will receive a diploma when they have completed the (official) study program and have obtained the required number of credits. If there are any other specific requirements that students need to have fulfilled, mention them here.
   * @return qualificationRequirements
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Normally, students will receive a diploma when they have completed the (official) study program and have obtained the required number of credits. If there are any other specific requirements that students need to have fulfilled, mention them here.")
  @JsonProperty(JSON_PROPERTY_QUALIFICATION_REQUIREMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<LanguageTypedString> getQualificationRequirements() {
    return qualificationRequirements;
  }


  @JsonProperty(JSON_PROPERTY_QUALIFICATION_REQUIREMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQualificationRequirements(List<LanguageTypedString> qualificationRequirements) {
    this.qualificationRequirements = qualificationRequirements;
  }


  public Course level(Level level) {
    
    this.level = level;
    return this;
  }

   /**
   * Get level
   * @return level
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LEVEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Level getLevel() {
    return level;
  }


  @JsonProperty(JSON_PROPERTY_LEVEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLevel(Level level) {
    this.level = level;
  }


  public Course enrollment(List<LanguageTypedString> enrollment) {
    
    this.enrollment = enrollment;
    return this;
  }

  public Course addEnrollmentItem(LanguageTypedString enrollmentItem) {
    if (this.enrollment == null) {
      this.enrollment = new ArrayList<>();
    }
    this.enrollment.add(enrollmentItem);
    return this;
  }

   /**
   * The extra information that is provided for enrollment
   * @return enrollment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[{language=en-GB, value=enrollment through SIS. [The limited implementation of Git Hub Markdown syntax](#tag/formatting-and-displaying-results-from-API) MAY be used for rich text representation.}]", value = "The extra information that is provided for enrollment")
  @JsonProperty(JSON_PROPERTY_ENROLLMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<LanguageTypedString> getEnrollment() {
    return enrollment;
  }


  @JsonProperty(JSON_PROPERTY_ENROLLMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnrollment(List<LanguageTypedString> enrollment) {
    this.enrollment = enrollment;
  }


  public Course resources(List<String> resources) {
    
    this.resources = resources;
    return this;
  }

  public Course addResourcesItem(String resourcesItem) {
    if (this.resources == null) {
      this.resources = new ArrayList<>();
    }
    this.resources.add(resourcesItem);
    return this;
  }

   /**
   * An overview of the literature and other resources that is used in this course (ECTS-recommended reading and other sources)
   * @return resources
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[book to be announced, on-line resource x]", value = "An overview of the literature and other resources that is used in this course (ECTS-recommended reading and other sources)")
  @JsonProperty(JSON_PROPERTY_RESOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getResources() {
    return resources;
  }


  @JsonProperty(JSON_PROPERTY_RESOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResources(List<String> resources) {
    this.resources = resources;
  }


  public Course assessment(List<LanguageTypedString> assessment) {
    
    this.assessment = assessment;
    return this;
  }

  public Course addAssessmentItem(LanguageTypedString assessmentItem) {
    if (this.assessment == null) {
      this.assessment = new ArrayList<>();
    }
    this.assessment.add(assessmentItem);
    return this;
  }

   /**
   * A description of the way exams for this course are taken (ECTS-assessment method and criteria).
   * @return assessment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[{language=en-GB, value=Exam on campus}]", value = "A description of the way exams for this course are taken (ECTS-assessment method and criteria).")
  @JsonProperty(JSON_PROPERTY_ASSESSMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<LanguageTypedString> getAssessment() {
    return assessment;
  }


  @JsonProperty(JSON_PROPERTY_ASSESSMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssessment(List<LanguageTypedString> assessment) {
    this.assessment = assessment;
  }


  public Course link(URI link) {
    
    this.link = link;
    return this;
  }

   /**
   * URL of the course&#39;s website
   * @return link
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://osiris.uu.nl/osiris_student_uuprd/OnderwijsCatalogusZoekCursus.do#submitForm?cursuscode=INFOMQNM", value = "URL of the course's website")
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getLink() {
    return link;
  }


  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLink(URI link) {
    this.link = link;
  }


  public Course educationSpecification(CoursePropertiesEducationSpecification educationSpecification) {
    
    this.educationSpecification = educationSpecification;
    return this;
  }

   /**
   * Get educationSpecification
   * @return educationSpecification
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EDUCATION_SPECIFICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CoursePropertiesEducationSpecification getEducationSpecification() {
    return educationSpecification;
  }


  @JsonProperty(JSON_PROPERTY_EDUCATION_SPECIFICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEducationSpecification(CoursePropertiesEducationSpecification educationSpecification) {
    this.educationSpecification = educationSpecification;
  }


  public Course addresses(List<Address> addresses) {
    
    this.addresses = addresses;
    return this;
  }

  public Course addAddressesItem(Address addressesItem) {
    if (this.addresses == null) {
      this.addresses = new ArrayList<>();
    }
    this.addresses.add(addressesItem);
    return this;
  }

   /**
   * Addresses for this course
   * @return addresses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Addresses for this course")
  @JsonProperty(JSON_PROPERTY_ADDRESSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Address> getAddresses() {
    return addresses;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddresses(List<Address> addresses) {
    this.addresses = addresses;
  }


  public Course otherCodes(List<IdentifierEntry> otherCodes) {
    
    this.otherCodes = otherCodes;
    return this;
  }

  public Course addOtherCodesItem(IdentifierEntry otherCodesItem) {
    if (this.otherCodes == null) {
      this.otherCodes = new ArrayList<>();
    }
    this.otherCodes.add(otherCodesItem);
    return this;
  }

   /**
   * An array of additional human readable codes/identifiers for the entity being described.
   * @return otherCodes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An array of additional human readable codes/identifiers for the entity being described.")
  @JsonProperty(JSON_PROPERTY_OTHER_CODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<IdentifierEntry> getOtherCodes() {
    return otherCodes;
  }


  @JsonProperty(JSON_PROPERTY_OTHER_CODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOtherCodes(List<IdentifierEntry> otherCodes) {
    this.otherCodes = otherCodes;
  }


  public Course consumers(List<Consumer> consumers) {
    
    this.consumers = consumers;
    return this;
  }

  public Course addConsumersItem(Consumer consumersItem) {
    if (this.consumers == null) {
      this.consumers = new ArrayList<>();
    }
    this.consumers.add(consumersItem);
    return this;
  }

   /**
   * The additional consumer elements that can be provided, see the [documentation on support for specific consumers](https://open-education-api.github.io/specification/#/consumers) for more information about this mechanism.
   * @return consumers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{$ref=../consumers/RIO/V1/examples/Course.yaml}", value = "The additional consumer elements that can be provided, see the [documentation on support for specific consumers](https://open-education-api.github.io/specification/#/consumers) for more information about this mechanism.")
  @JsonProperty(JSON_PROPERTY_CONSUMERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Consumer> getConsumers() {
    return consumers;
  }


  @JsonProperty(JSON_PROPERTY_CONSUMERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConsumers(List<Consumer> consumers) {
    this.consumers = consumers;
  }


  public Course ext(Object ext) {
    
    this.ext = ext;
    return this;
  }

   /**
   * Object for additional non-standard attributes
   * @return ext
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Object for additional non-standard attributes")
  @JsonProperty(JSON_PROPERTY_EXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getExt() {
    return ext;
  }


  @JsonProperty(JSON_PROPERTY_EXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExt(Object ext) {
    this.ext = ext;
  }


  public Course programs(List<ProgramPropertiesChildrenInner> programs) {
    
    this.programs = programs;
    return this;
  }

  public Course addProgramsItem(ProgramPropertiesChildrenInner programsItem) {
    if (this.programs == null) {
      this.programs = new ArrayList<>();
    }
    this.programs.add(programsItem);
    return this;
  }

   /**
   * The program of which this course is a part of. This object is [&#x60;expandable&#x60;](#tag/program_model)
   * @return programs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The program of which this course is a part of. This object is [`expandable`](#tag/program_model)")
  @JsonProperty(JSON_PROPERTY_PROGRAMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ProgramPropertiesChildrenInner> getPrograms() {
    return programs;
  }


  @JsonProperty(JSON_PROPERTY_PROGRAMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrograms(List<ProgramPropertiesChildrenInner> programs) {
    this.programs = programs;
  }


  public Course coordinators(List<ProgramPropertiesCoordinatorsInner> coordinators) {
    
    this.coordinators = coordinators;
    return this;
  }

  public Course addCoordinatorsItem(ProgramPropertiesCoordinatorsInner coordinatorsItem) {
    if (this.coordinators == null) {
      this.coordinators = new ArrayList<>();
    }
    this.coordinators.add(coordinatorsItem);
    return this;
  }

   /**
   * The person(s) responsible for this course. This object is [&#x60;expandable&#x60;](#tag/person_model)
   * @return coordinators
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The person(s) responsible for this course. This object is [`expandable`](#tag/person_model)")
  @JsonProperty(JSON_PROPERTY_COORDINATORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ProgramPropertiesCoordinatorsInner> getCoordinators() {
    return coordinators;
  }


  @JsonProperty(JSON_PROPERTY_COORDINATORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCoordinators(List<ProgramPropertiesCoordinatorsInner> coordinators) {
    this.coordinators = coordinators;
  }


  public Course organization(CoursePropertiesOrganization organization) {
    
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CoursePropertiesOrganization getOrganization() {
    return organization;
  }


  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrganization(CoursePropertiesOrganization organization) {
    this.organization = organization;
  }


  public Course validFrom(LocalDate validFrom) {
    
    this.validFrom = validFrom;
    return this;
  }

   /**
   * The first day this course is valid (inclusive).
   * @return validFrom
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The first day this course is valid (inclusive).")
  @JsonProperty(JSON_PROPERTY_VALID_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getValidFrom() {
    return validFrom;
  }


  @JsonProperty(JSON_PROPERTY_VALID_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidFrom(LocalDate validFrom) {
    this.validFrom = validFrom;
  }


  public Course validTo(LocalDate validTo) {
    
    this.validTo = validTo;
    return this;
  }

   /**
   * The day this course ceases to be valid (e.g. exclusive).
   * @return validTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The day this course ceases to be valid (e.g. exclusive).")
  @JsonProperty(JSON_PROPERTY_VALID_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getValidTo() {
    return validTo;
  }


  @JsonProperty(JSON_PROPERTY_VALID_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidTo(LocalDate validTo) {
    this.validTo = validTo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Course course = (Course) o;
    return Objects.equals(this.courseId, course.courseId) &&
        Objects.equals(this.primaryCode, course.primaryCode) &&
        Objects.equals(this.name, course.name) &&
        Objects.equals(this.abbreviation, course.abbreviation) &&
        Objects.equals(this.studyLoad, course.studyLoad) &&
        Objects.equals(this.modeOfDelivery, course.modeOfDelivery) &&
        Objects.equals(this.duration, course.duration) &&
        Objects.equals(this.firstStartDate, course.firstStartDate) &&
        Objects.equals(this.description, course.description) &&
        Objects.equals(this.teachingLanguage, course.teachingLanguage) &&
        Objects.equals(this.fieldsOfStudy, course.fieldsOfStudy) &&
        Objects.equals(this.learningOutcomes, course.learningOutcomes) &&
        Objects.equals(this.admissionRequirements, course.admissionRequirements) &&
        Objects.equals(this.qualificationRequirements, course.qualificationRequirements) &&
        Objects.equals(this.level, course.level) &&
        Objects.equals(this.enrollment, course.enrollment) &&
        Objects.equals(this.resources, course.resources) &&
        Objects.equals(this.assessment, course.assessment) &&
        Objects.equals(this.link, course.link) &&
        Objects.equals(this.educationSpecification, course.educationSpecification) &&
        Objects.equals(this.addresses, course.addresses) &&
        Objects.equals(this.otherCodes, course.otherCodes) &&
        Objects.equals(this.consumers, course.consumers) &&
        Objects.equals(this.ext, course.ext) &&
        Objects.equals(this.programs, course.programs) &&
        Objects.equals(this.coordinators, course.coordinators) &&
        Objects.equals(this.organization, course.organization) &&
        Objects.equals(this.validFrom, course.validFrom) &&
        Objects.equals(this.validTo, course.validTo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(courseId, primaryCode, name, abbreviation, studyLoad, modeOfDelivery, duration, firstStartDate, description, teachingLanguage, fieldsOfStudy, learningOutcomes, admissionRequirements, qualificationRequirements, level, enrollment, resources, assessment, link, educationSpecification, addresses, otherCodes, consumers, ext, programs, coordinators, organization, validFrom, validTo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Course {\n");
    sb.append("    courseId: ").append(toIndentedString(courseId)).append("\n");
    sb.append("    primaryCode: ").append(toIndentedString(primaryCode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    abbreviation: ").append(toIndentedString(abbreviation)).append("\n");
    sb.append("    studyLoad: ").append(toIndentedString(studyLoad)).append("\n");
    sb.append("    modeOfDelivery: ").append(toIndentedString(modeOfDelivery)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    firstStartDate: ").append(toIndentedString(firstStartDate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    teachingLanguage: ").append(toIndentedString(teachingLanguage)).append("\n");
    sb.append("    fieldsOfStudy: ").append(toIndentedString(fieldsOfStudy)).append("\n");
    sb.append("    learningOutcomes: ").append(toIndentedString(learningOutcomes)).append("\n");
    sb.append("    admissionRequirements: ").append(toIndentedString(admissionRequirements)).append("\n");
    sb.append("    qualificationRequirements: ").append(toIndentedString(qualificationRequirements)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    enrollment: ").append(toIndentedString(enrollment)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    assessment: ").append(toIndentedString(assessment)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    educationSpecification: ").append(toIndentedString(educationSpecification)).append("\n");
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("    otherCodes: ").append(toIndentedString(otherCodes)).append("\n");
    sb.append("    consumers: ").append(toIndentedString(consumers)).append("\n");
    sb.append("    ext: ").append(toIndentedString(ext)).append("\n");
    sb.append("    programs: ").append(toIndentedString(programs)).append("\n");
    sb.append("    coordinators: ").append(toIndentedString(coordinators)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    validFrom: ").append(toIndentedString(validFrom)).append("\n");
    sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

